codecov:
  branch: master  # override the default branch
  bot: trilliwon  # set user whom will be the consumer of oauth requests

coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: down # default down
  range: 50...60 # default 70...90. red...green

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        branches: null  # all branches by default
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"  # customize the message
        attachments: "sunburst, diff"
        only_pulls: false
        flags: null
        paths: null

    email:
      default:
        to:
          - trilliwon@gmail.com
          - &author
        threshold: 1%
        only_pulls: false
        layout: reach, diff, flags, files
        flags: null
        paths: null

  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 1%
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder
    
    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

  flags:
    integration:
      branches:
        - master
      ignore:
        - Example/*

  ignore: # files and folders for processing
    - Example/*

comment:
  layout: reach, diff, flags, files
  branches: *
  behavior: default # defualt = posts once then update, posts new if delete
                    # once = post once then updates
                    # new = delete old, post new
                    # spammy = post new