language: swift
osx_image: xcode8.3

script: 
  - xcodebuild test -project NaturalKorean.xcodeproj -scheme NaturalKorean -destination 'platform=iOS Simulator,name=iPhone 7' 
after_success: bash <(curl -s https://codecov.io/bash) -J 'NaturalKorean'