language: swift
osx_image: xcode8.3
script: travis/travis.sh

before_install:
  - gem install xcpretty
after_success:
  - travis/travis_after_success.sh
  - bash <(curl -s https://codecov.io/bash) -J 'NaturalKorean'
  
after_failure:
  - travis/travis_after_failure.sh